"use client";
/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-img-element */

import { useCallback, useEffect, useState } from "react";
import { useERPStore, erpApi } from "@/src/lib/erp-store";

export type PhaseTwoModule = "service-setup" | "leave" | "payments" | "marketing" | "time-slots" | "audit-log";
type Item = Record<string, unknown> & { id: string };
const input = "w-full rounded-xl border border-zinc-200 px-3 py-2 text-sm outline-none focus:border-zinc-900";
const panel = "rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm";
const button = "rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white hover:bg-zinc-800";
const list = <T,>(value: unknown) => Array.isArray(value) ? value as T[] : ((value as { data?: T[] })?.data ?? []);

export default function PhaseTwoConsole({ module }: { module: PhaseTwoModule }) {
  const titles: Record<PhaseTwoModule, [string, string]> = {
    "service-setup": ["Service setup", "Organize services and assign staff skills."], leave: ["Leave requests", "Apply, approve, reject, or cancel staff leave."], payments: ["Payments & refunds", "Record collections and refund completed payments."], marketing: ["Offers & gallery", "Manage promotions and website gallery images."], "time-slots": ["Time slots", "Create and block online-booking capacity by branch."], "audit-log": ["Audit log", "Review salon administration activity."],
  };
  const [title, subtitle] = titles[module];
  return <div className="mx-auto max-w-7xl space-y-6 pb-12"><header className={panel}><h1 className="text-2xl font-bold text-zinc-950">{title}</h1><p className="mt-1 text-sm text-zinc-500">{subtitle}</p></header>{module === "service-setup" && <ServiceSetup />}{module === "leave" && <LeaveRequests />}{module === "payments" && <Payments />}{module === "marketing" && <Marketing />}{module === "time-slots" && <TimeSlots />}{module === "audit-log" && <AuditLog />}</div>;
}

function ServiceSetup() {
  const { employees, services } = useERPStore(); const [categories, setCategories] = useState<Item[]>([]); const [employeeId, setEmployeeId] = useState(""); const [skills, setSkills] = useState<Item[]>([]);
  const load = useCallback(async () => setCategories(list<Item>(await erpApi("/service-categories"))), []); useEffect(() => { void load(); }, [load]);
  const loadSkills = async (id: string) => { setEmployeeId(id); setSkills(id ? list<Item>(await erpApi(`/employee-services/employees/${id}`)) : []); };
  return <div className="grid gap-6 lg:grid-cols-2"><section className={panel}><h2 className="font-bold">Service categories</h2><form className="mt-4 grid gap-2" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void erpApi("/service-categories", { method: "POST", body: JSON.stringify({ name: f.get("name"), description: f.get("description") || null }) }).then(() => { e.currentTarget.reset(); return load(); }); }}><input required name="name" placeholder="Hair, Skin, Spa…" className={input}/><input name="description" placeholder="Optional description" className={input}/><button className={button}>Add category</button></form><div className="mt-4 space-y-2">{categories.map((c) => <div key={c.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span><b>{String(c.name)}</b><span className="ml-2 text-zinc-500">{String(c.serviceCount ?? 0)} services</span></span><button onClick={() => void erpApi(`/service-categories/${c.id}`, { method: "DELETE" }).then(load)} className="text-rose-700">Delete</button></div>)}</div></section><section className={panel}><h2 className="font-bold">Staff service skills</h2><select value={employeeId} onChange={(e) => void loadSkills(e.target.value)} className={`mt-4 ${input}`}><option value="">Select employee</option>{employees.map((e) => <option key={e.id} value={e.id}>{e.name}</option>)}</select>{employeeId && <div className="mt-4 space-y-2">{services.map((service) => { const assigned = skills.some((skill) => skill.id === service.id); return <label key={service.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>{service.name}</span><input type="checkbox" checked={assigned} onChange={() => void erpApi(assigned ? `/employee-services/${employeeId}/${service.id}` : "/employee-services", { method: assigned ? "DELETE" : "POST", body: assigned ? undefined : JSON.stringify({ employeeId, serviceId: service.id }) }).then(() => loadSkills(employeeId))}/></label>; })}</div>}</section></div>;
}

/* eslint-disable @typescript-eslint/no-unused-vars -- retained temporarily while the safer leave UI replaces this legacy view. */
function Leave() {
  const { employees } = useERPStore(); const [items, setItems] = useState<Item[]>([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const load = useCallback(async () => { try { setItems(list<Item>(await erpApi("/leave-requests?limit=100"))); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load leave requests."); } }, []); useEffect(() => { void load(); }, [load]);
  return <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form className={panel} onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void erpApi("/leave-requests", { method: "POST", body: JSON.stringify({ employeeId: f.get("employeeId"), startDate: f.get("startDate"), endDate: f.get("endDate"), reason: f.get("reason") || null }) }).then(() => { e.currentTarget.reset(); return load(); }); }}><h2 className="font-bold">New leave request</h2><div className="mt-4 space-y-3"><select required name="employeeId" className={input}><option value="">Select employee</option>{employees.map((e) => <option key={e.id} value={e.id}>{e.name}</option>)}</select><input required type="date" name="startDate" className={input}/><input required type="date" name="endDate" className={input}/><textarea name="reason" placeholder="Reason" className={input}/><button className={button}>Submit leave</button></div></form><section className={panel}><h2 className="font-bold">Requests</h2><div className="mt-4 space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border p-4 text-sm"><b>{String(item.employeeName)}</b><p className="mt-1 text-zinc-500">{String(item.startDate).slice(0,10)} to {String(item.endDate).slice(0,10)} · {String(item.status)}</p><p className="mt-1">{String(item.reason ?? "No reason supplied")}</p>{item.status === "PENDING" && <div className="mt-3 flex gap-2">{["APPROVED", "REJECTED", "CANCELLED"].map((status) => <button key={status} onClick={() => void erpApi(`/leave-requests/${item.id}`, { method: "PATCH", body: JSON.stringify({ status }) }).then(load)} className="rounded-lg border px-2 py-1 text-xs">{status}</button>)}</div>}</article>)}</div></section></div>;
}

/* eslint-enable @typescript-eslint/no-unused-vars */
function LeaveRequests() {
  const { employees } = useERPStore();
  const [items, setItems] = useState<Item[]>([]);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const load = useCallback(async () => {
    try { setItems(list<Item>(await erpApi("/leave-requests?limit=100"))); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load leave requests."); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement);
    const startDate = String(form.get("startDate")); const endDate = String(form.get("endDate"));
    if (endDate < startDate) { setError("End date must be on or after the start date."); return; }
    setSaving(true); setError("");
    try { await erpApi("/leave-requests", { method: "POST", body: JSON.stringify({ employeeId: form.get("employeeId"), startDate, endDate, reason: form.get("reason") || null }) }); formElement.reset(); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Could not submit leave request."); }
    finally { setSaving(false); }
  };
  const changeStatus = async (id: string, status: string) => {
    setSaving(true); setError("");
    try { await erpApi(`/leave-requests/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update leave request."); }
    finally { setSaving(false); }
  };
  return <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form className={panel} onSubmit={submit}><h2 className="font-bold">New leave request</h2><p className="mt-1 text-sm text-zinc-500">Submit one request per employee and date range.</p>{error && <p role="alert" className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-4 space-y-3"><select required name="employeeId" className={input}><option value="">Select employee</option>{employees.map((e) => <option key={e.id} value={e.id}>{e.name}</option>)}</select><input required type="date" name="startDate" aria-label="Start date" className={input}/><input required type="date" name="endDate" aria-label="End date" className={input}/><textarea name="reason" placeholder="Reason (optional)" className={input}/><button disabled={saving} type="submit" className={`${button} disabled:opacity-50`}>{saving ? "Saving..." : "Submit leave"}</button></div></form><section className={panel}><h2 className="font-bold">Requests</h2><div className="mt-4 space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border p-4 text-sm"><b>{String(item.employeeName)}</b><p className="mt-1 text-zinc-500">{String(item.startDate).slice(0, 10)} to {String(item.endDate).slice(0, 10)} · {String(item.status)}</p><p className="mt-1">{String(item.reason ?? "No reason supplied")}</p>{item.status === "PENDING" && <div className="mt-3 flex flex-wrap gap-2">{["APPROVED", "REJECTED", "CANCELLED"].map((status) => <button type="button" disabled={saving} key={status} onClick={() => void changeStatus(item.id, status)} className="rounded-lg border px-2 py-1 text-xs disabled:opacity-50">{status}</button>)}</div>}</article>)}{!items.length && <p className="py-8 text-center text-sm text-zinc-500">No leave requests yet.</p>}</div></section></div>;
}

function Payments() {
  const { invoices, customers } = useERPStore(); const [items, setItems] = useState<Item[]>([]); const load = useCallback(async () => setItems(list<Item>(await erpApi("/payments"))), []); useEffect(() => { void load(); }, [load]);
  return <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form className={panel} onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void erpApi("/payments", { method: "POST", body: JSON.stringify({ invoiceId: f.get("invoiceId") || null, customerId: f.get("customerId") || null, amount: Number(f.get("amount")), method: f.get("method"), transactionId: f.get("transactionId") || null }) }).then(() => { e.currentTarget.reset(); return load(); }); }}><h2 className="font-bold">Record payment</h2><div className="mt-4 space-y-3"><select name="invoiceId" className={input}><option value="">No invoice</option>{invoices.map((i) => <option key={i.id} value={i.id}>{i.invoiceNumber ?? i.id} · ₹{i.amount}</option>)}</select><select name="customerId" className={input}><option value="">No customer</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input required type="number" min="1" name="amount" placeholder="Amount" className={input}/><select name="method" className={input}>{["CASH","CARD","UPI","WALLET","ONLINE"].map((x) => <option key={x}>{x}</option>)}</select><input name="transactionId" placeholder="Transaction reference" className={input}/><button className={button}>Record payment</button></div></form><section className={panel}><h2 className="font-bold">Payment ledger</h2><div className="mt-4 space-y-2">{items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>₹{String(item.amount)} · {String(item.method)} · <b>{String(item.status)}</b></span>{item.status !== "REFUNDED" && <button onClick={() => void erpApi(`/payments/${item.id}/refund`, { method: "POST" }).then(load)} className="text-rose-700">Refund</button>}</div>)}</div></section></div>;
}

function Marketing() {
  const [offers, setOffers] = useState<Item[]>([]); const [gallery, setGallery] = useState<Item[]>([]); const load = useCallback(async () => { const [o, g] = await Promise.all([erpApi("/offers"), erpApi("/gallery")]); setOffers(list<Item>(o)); setGallery(list<Item>(g)); }, []); useEffect(() => { void load(); }, [load]);
  return <div className="grid gap-6 lg:grid-cols-2"><section className={panel}><h2 className="font-bold">Promotional offers</h2><form className="mt-4 grid gap-2" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void erpApi("/offers", { method: "POST", body: JSON.stringify({ title: f.get("title"), discount: Number(f.get("discount")), discountType: f.get("discountType"), startDate: f.get("startDate"), endDate: f.get("endDate"), description: f.get("description") || null, bannerImage: f.get("bannerImage") || null, isActive: true }) }).then(() => { e.currentTarget.reset(); return load(); }); }}><input required name="title" placeholder="Festival special" className={input}/><div className="grid grid-cols-2 gap-2"><input required type="number" min="1" name="discount" placeholder="Discount" className={input}/><select name="discountType" className={input}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed amount</option></select></div><div className="grid grid-cols-2 gap-2"><input required type="date" name="startDate" className={input}/><input required type="date" name="endDate" className={input}/></div><input name="bannerImage" placeholder="Banner image URL (optional)" className={input}/><textarea name="description" placeholder="Offer details" className={input}/><button className={button}>Create offer</button></form><div className="mt-4 space-y-2">{offers.map((offer) => <div key={offer.id} className="flex justify-between rounded-xl border p-3 text-sm"><span><b>{String(offer.title)}</b> · {String(offer.discount)} {String(offer.discountType)}</span><button onClick={() => void erpApi(`/offers/${offer.id}`, { method: "DELETE" }).then(load)} className="text-rose-700">Delete</button></div>)}</div></section><section className={panel}><h2 className="font-bold">Website gallery</h2><form className="mt-4 flex gap-2" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void erpApi("/gallery", { method: "POST", body: JSON.stringify({ imageUrl: f.get("imageUrl"), title: f.get("title") || null }) }).then(() => { e.currentTarget.reset(); return load(); }); }}><input required type="url" name="imageUrl" placeholder="Image URL" className={input}/><input name="title" placeholder="Caption" className={input}/><button className={button}>Add</button></form><div className="mt-4 grid grid-cols-2 gap-3">{gallery.map((image) => <figure key={image.id} className="overflow-hidden rounded-xl border"><img src={String(image.imageUrl)} alt={String(image.title ?? "Salon gallery")} className="h-28 w-full object-cover"/><figcaption className="flex justify-between gap-2 p-2 text-xs"><span className="truncate">{String(image.title ?? "Untitled")}</span><button onClick={() => void erpApi(`/gallery/${image.id}`, { method: "DELETE" }).then(load)} className="text-rose-700">Delete</button></figcaption></figure>)}</div></section></div>;
}

function TimeSlots() {
  const { branches } = useERPStore(); const [branchId, setBranchId] = useState(""); const [date, setDate] = useState(""); const [items, setItems] = useState<Item[]>([]); const load = useCallback(async () => { if (branchId) setItems(list<Item>(await erpApi(`/time-slots?branchId=${encodeURIComponent(branchId)}${date ? `&date=${date}` : ""}`))); }, [branchId, date]); useEffect(() => { void load(); }, [load]);
  return <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form className={panel} onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void erpApi("/time-slots", { method: "POST", body: JSON.stringify({ branchId: f.get("branchId"), startTime: f.get("startTime"), endTime: f.get("endTime"), capacity: Number(f.get("capacity")) }) }).then(load); }}><h2 className="font-bold">Create time slot</h2><div className="mt-4 space-y-3"><select required name="branchId" value={branchId} onChange={(e) => setBranchId(e.target.value)} className={input}><option value="">Select branch</option>{branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select><input required type="datetime-local" name="startTime" className={input}/><input required type="datetime-local" name="endTime" className={input}/><input required type="number" min="1" name="capacity" defaultValue="1" className={input}/><button className={button}>Create slot</button></div></form><section className={panel}><div className="flex gap-3"><input type="date" value={date} onChange={(e) => setDate(e.target.value)} className={input}/><button onClick={() => void load()} className={button}>Load slots</button></div><div className="mt-4 space-y-2">{items.map((slot) => <div key={slot.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>{new Date(String(slot.startTime)).toLocaleString()} → {new Date(String(slot.endTime)).toLocaleTimeString()} · capacity {String(slot.capacity)}</span><button onClick={() => void erpApi(`/time-slots/${slot.id}/${slot.isAvailable ? "block" : "release"}`, { method: "PATCH" }).then(load)} className="rounded-lg border px-2 py-1">{slot.isAvailable ? "Block" : "Release"}</button></div>)}</div></section></div>;
}

function AuditLog() {
  const [items, setItems] = useState<Item[]>([]); const [search, setSearch] = useState(""); const load = useCallback(async () => setItems(list<Item>(await erpApi(`/salon-audit-logs?limit=100${search ? `&search=${encodeURIComponent(search)}` : ""}`))), [search]); useEffect(() => { void load(); }, [load]);
  return <section className={panel}><div className="flex gap-3"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search entity or action" className={input}/><button onClick={() => void load()} className={button}>Search</button></div><div className="mt-5 divide-y">{items.map((item) => <div key={item.id} className="py-3 text-sm"><div className="flex justify-between gap-4"><b>{String(item.action)} · {String(item.entity)}</b><span className="text-zinc-500">{new Date(String(item.createdAt)).toLocaleString()}</span></div><p className="mt-1 text-xs text-zinc-500">{String((item.user as { name?: string } | null)?.name ?? "System")} · {String(item.entityId ?? "")}</p></div>)}{!items.length && <p className="py-8 text-center text-sm text-zinc-500">No audit entries found.</p>}</div></section>;
}
