"use client";

import { useState } from "react";
import { erpApi } from "@/src/lib/erp-store";

export default function UploadConsole() {
  const [file, setFile] = useState<File | null>(null); const [url, setUrl] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const upload = async (event: React.FormEvent) => { event.preventDefault(); if (!file) return; setBusy(true); setError(""); try { const data = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Could not read the selected file.")); reader.readAsDataURL(file); }); const result = await erpApi<{ url: string }>("/uploads", { method: "POST", body: JSON.stringify({ fileName: file.name, contentType: file.type, data }) }); setUrl(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5000/api"}${result.url}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Upload failed."); } finally { setBusy(false); } };
  return <section className="mx-auto max-w-2xl rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold">File uploads</h1><p className="mt-1 text-sm text-zinc-500">Upload images or PDFs up to 5 MB. Use the returned URL in gallery, offers, or website content.</p><form onSubmit={upload} className="mt-6 space-y-4"><input required type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="block w-full text-sm"/><button disabled={!file || busy} className="rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Uploading…" : "Upload file"}</button></form>{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{url && <div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><p className="font-semibold">Upload complete</p><a className="mt-2 block break-all underline" href={url} target="_blank" rel="noreferrer">{url}</a></div>}</section>;
}
